### ISSUE TITLE
Wrong reporting in some curcumpstances.

### ISSUE THREAD

**Issue by hickscorp** [parroty/excoveralls#92]
I'm not sure whether this is an actual issue or something I'm missing. Feel free to close this issue in the later case.

Somehow, ExCoveralls reports 0 hits on a `with` keyword usage:

![image](https://cloud.githubusercontent.com/assets/822933/21749586/951a9bda-d599-11e6-9898-0f435e6846c7.png)

**Comment by parroty** [comment]
Thanks for the report. It might be related to the https://github.com/parroty/excoveralls/issues/59, and haven't been able to find good ways to resolve the issue.

One possible workaround is to define `with` statement as stop words. It makes the matching statements as `not related` instead of `not covered`.

- https://github.com/parroty/excoveralls#coverallsjson

**Comment by hickscorp** [comment]
@parroty It indeed seems to be the same issue. Appologies for the noise, closing this one.
